version: '3'

services:
    mongodb:
        image: mongodb/mongodb-atlas-local
        ports:
            - "${MONGO_PORT}:${MONGO_PORT}"
        environment:
            - MONGODB_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        volumes:
            - mongodb_data:/data/db
            - mongodb_config:/data/configdb
        networks:
            - smartstorage-net

    sftp:
        build:
            dockerfile: ./Dockerfile_Sftp
            args:
                USER: ${SFTP_USERNAME}
        env_file:
            - .env
        command: ${SFTP_USERNAME}:${SFTP_PASSWORD}:${SFTP_PORT}
        ports:
            - "${SFTP_PORT}:${SFTP_PORT}"
        volumes:
            - sftp:/home/${SFTP_USERNAME}/files
        networks:
            - smartstorage-net

    front:
        build: ./front
        container_name: angular
        ports:
            - "${ANGULAR_PORT}:${ANGULAR_PORT}"
        env_file:
            - .env
        networks:
            - smartstorage-net
        depends_on:
            - back

    back:
        build: ./back
        container_name: springboot
        ports:
            - "${API_PORT}:${API_PORT}"
        env_file:
            - .env
        networks:
            - smartstorage-net
        command: bash -c "ssh-keyscan -H -t rsa,ecdsa -p ${SFTP_PORT} sftp >> /usr/src/app/known_hosts && mvn spring-boot:run"
        depends_on:
            mongodb:
                  condition: service_healthy
            sftp:
                  condition: service_started

    rag:
        build:
            dockerfile: ./rag/Dockerfile
        ports:
            - "8000:8000"
        depends_on:
            #            rag-mongodb:
            #                condition: service_healthy
            ollama:
                condition: service_started
        env_file:
            - .env
        container_name: rag
        restart: always
        networks:
            - smartstorage-net

    ollama:
        build:
            dockerfile: ./Dockerfile_Ollama
        ports:
            - "4444:11434"
        volumes:
            - ollama_volume:/root/.ollama
        env_file:
            - .env
        container_name: ollama
        tty: true
        restart: always
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [ gpu ]
        networks:
            - smartstorage-net

networks:
    smartstorage-net:


volumes:
    mongodb:
    sftp:
    mongodb_data:
    mongodb_config:
    ollama_volume:

