services:
  mongodb:
    image: mongodb/mongodb-atlas-local
    container_name: mongodb
    env_file:
      - app/.env
    ports:
      - 27777:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    restart: always
    networks:
      - net

  app:
    build:
      dockerfile: ./app/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true
    env_file:
      - app/.env
    container_name: app
    restart: always
    networks:
      - net


  ollama:
    image: ollama/ollama:latest
    ports:
      - 4444:11434
    volumes:
      - ollama_vol:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    networks:
      - net


volumes:
  mongodb_data:
  mongodb_config:
  ollama_vol:

networks:
  net:
    driver: bridge

